Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -12,8 +12,8 @@ jobs:
     runs-on: ubuntu-latest
     env:
       DOCKER_IMAGE: 992382544923.dkr.ecr.us-east-1.amazonaws.com/aamirpatel #aamirpatel/cicdpy
-      #SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
-      #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     steps:
@@ -39,18 +39,18 @@ jobs:
         run: |
           docker push $DOCKER_IMAGE:${{ github.sha }}
           docker push $DOCKER_IMAGE:latest
-     # - name: Official SonarQube Scan
-     #   uses: SonarSource/sonarqube-scan-action@v3.0.0
-     #   with:
-     #     projectBaseDir: .
-     #     args: >
-     #       -Dsonar.projectKey=hackathon-proj -Dsonar.host.url=${{ env.SONAR_HOST_URL
-     #       }} -Dsonar.login=${{ env.SONAR_TOKEN }}
-     #       -Dsonar.working.directory=./.scannerwork
-     # - name: Print SonarQube Logs
-     #   run: >
-     #     ls -al .scannerwork
-     #     cat .scannerwork/report-task.txt || echo "report-task.txt not found"
+      - name: Official SonarQube Scan
+        uses: SonarSource/sonarqube-scan-action@v3.0.0
+        with:
+          projectBaseDir: .
+          args: >
+            -Dsonar.projectKey=hackathon-proj -Dsonar.host.url=${{ env.SONAR_HOST_URL
+            }} -Dsonar.login=${{ env.SONAR_TOKEN }}
+            -Dsonar.working.directory=./.scannerwork
+      - name: Print SonarQube Logs
+        run: >
+          ls -al .scannerwork
+          cat .scannerwork/report-task.txt || echo "report-task.txt not found"
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
